#!/bin/bash

clear
echo
echo
echo "Welcome to RocketRaja's Reconnaissance framework"

break = "=================================================================="

break
echo "choose your reconnaissance type"
echo "1. Active"
echo "2. Passive"
echo -n "Enter your choice (1 or 2):"
read  choice

$CHOICE

active(){


}

passive(){

}
